services:  
  kafka1:
    image: bitnami/kafka:latest
    container_name: kafka1
    ports:      
      - "9094:9094"    
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://kafka1:29092,CONTROLLER://:9093,SASL_PLAINTEXT://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:29092,SASL_PLAINTEXT://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,SASL_PLAINTEXT:SASL_PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=SASL_PLAINTEXT      
      - KAFKA_CFG_SASL_ENABLED_MECHANISMS=PLAIN
      - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
      - KAFKA_INTER_BROKER_USER=kafka1
      - KAFKA_INTER_BROKER_PASSWORD=kafka1      
    networks:
      - network          

  kafka2:
    image: bitnami/kafka:latest
    container_name: kafka2
    ports:      
      - "9092:9092"    
    environment:
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=2@kafka2:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://kafka2:29092,CONTROLLER://:9093,SASL_PLAINTEXT://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka2:29092,SASL_PLAINTEXT://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,SASL_PLAINTEXT:SASL_PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=SASL_PLAINTEXT      
      - KAFKA_CFG_SASL_ENABLED_MECHANISMS=PLAIN
      - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
      - KAFKA_INTER_BROKER_USER=kafka2
      - KAFKA_INTER_BROKER_PASSWORD=kafka2
    networks:
      - network                

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    environment:
      - KAFKA_CLUSTERS_0_NAME=kafka1
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka1:29092      
      - KAFKA_CLUSTERS_1_NAME=kafka2
      - KAFKA_CLUSTERS_1_BOOTSTRAP_SERVERS=kafka2:29092            
    ports:
      - '8080:8080'
    depends_on:
      - kafka1
      - kafka2      
    networks:
      - network          

  init-kafka:
    image: confluentinc/cp-kafka:7.3.3
    entrypoint: [ '/bin/sh', '-c' ]
    container_name: init-kafka
    command: |
      "
      # blocks until kafka is reachable
      kafka-topics --bootstrap-server kafka1:29092 --list

      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server kafka1:29092 --create --if-not-exists --topic msg-default --replication-factor 1 --partitions 1      

      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server kafka1:29092 --list

      # blocks until kafka is reachable
      kafka-topics --bootstrap-server kafka2:29092 --list

      echo -e 'Creating kafka topics'      
      kafka-topics --bootstrap-server kafka2:29092 --create --if-not-exists --topic msg-deadletter --replication-factor 1 --partitions 1
      kafka-topics --bootstrap-server kafka2:29092 --create --if-not-exists --topic msg-retry --replication-factor 1 --partitions 1

      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server kafka2:29092 --list      
      "
    depends_on:
      - kafka1
      - kafka2
    networks:
      - network    

networks:
  network:
    driver: bridge          